# -*- coding: utf-8 -*-
"""Taxonomia da plataforma: matérias (áreas) e temas.

Os nomes de área e o peso esperado por prova vêm da análise de padrões
2021-2026 do próprio autor; os nomes de tema vêm dos títulos das aulas do
ebook, das áreas do simulado e das frentes dos cartões. Nada aqui é
conteúdo médico novo — é apenas o índice usado para organizar o material.
"""

# (slug, nome, sigla, questoes_esperadas_2027, subtitulo)
AREAS = [
    ("coloproctologia", "Coloproctologia", "CR", 8, "Cólon, reto e ânus"),
    ("perioperatorio", "Pré e pós-operatório", "PPO", 7, "Nutrição, infecção e terapia intensiva"),
    ("vias-biliares", "Vias biliares e vesícula", "VB", 5, "Da colecistite ao colangiocarcinoma"),
    ("estomago-duodeno", "Estômago e duodeno", "ED", 5, "Úlcera, HDA e câncer gástrico"),
    ("oncologia", "Oncologia geral", "ONC", 5, "Princípios, estadiamento e genética"),
    ("pancreas", "Pâncreas", "PAN", 4, "Pancreatite, cistos e adenocarcinoma"),
    ("trauma", "Trauma", "TRA", 4, "ATLS 11ª edição"),
    ("hernias", "Hérnias e parede abdominal", "HPA", 4, "Inguinal, incisional e fechamento"),
    ("esofago", "Esôfago", "ESO", 4, "Motilidade, DRGE e neoplasia"),
    ("apendice-delgado", "Apêndice e delgado", "AID", 4, "Apendicite, obstrução e TNE"),
    ("figado", "Fígado e hipertensão portal", "FIG", 3, "Tumores, abscessos e cirrose"),
    ("etica", "Ética e medicina legal", "ETI", 3, "Resoluções do CFM e bioética"),
    ("urologia", "Urologia cirúrgica", "URO", 3, "Litíase, escroto agudo e trauma"),
    ("endocrino-cp", "Endócrino e cabeça-pescoço", "CP", 3, "Tireoide, paratireoide e adrenal"),
    ("anestesia-via-aerea", "Anestesia e via aérea", "AVA", 2, "Indução, bloqueio e ventilação"),
    ("baco-transplante", "Baço e transplante", "BHT", 2, "Esplenectomia e imunossupressão"),
    ("vascular", "Cirurgia vascular", "VAS", 2, "Aneurismas, isquemia e TVP"),
    ("toracica", "Cirurgia torácica", "TOR", 2, "Pleura, pulmão e traqueia"),
    ("pele-sarcomas", "Pele, partes moles e sarcomas", "PPM", 2, "Melanoma, queimaduras e reconstrução"),
    ("videolaparoscopia", "Videolaparoscopia e robótica", "VLR", 2, "Fisiologia e complicações do pneumoperitônio"),
    ("bariatrica", "Bariátrica e metabólica", "BAR", 2, "Indicações, técnicas e complicações"),
    ("pediatrica", "Cirurgia pediátrica", "PED", 1, "Do recém-nascido ao lactente"),
    ("mama", "Mama", "MAM", 1, "Nódulo, rastreio e reconstrução"),
    ("anatomia", "Anatomia cirúrgica", "ANA", 1, "Tronco celíaco, porta e canal anal"),
    ("nefrologia", "Nefrologia e função renal", "NEF", 0, "Doença renal crônica e TFG"),
    ("transversais", "Escores, eponímias e números", "TRV", 0, "A camada que atravessa todas as áreas"),
]

# (area_slug, tema, [palavras-chave])  — a ordem importa: o primeiro casamento
# mais longo vence. Palavras-chave são comparadas sem acento e em minúsculas.
TEMAS = [
    # ── Vias biliares ────────────────────────────────────────────────
    ("vias-biliares", "Colecistite aguda e critérios de Tóquio",
     ["colecistite", "tokyo guidelines", "criterios de toquio", "sinal de murphy", "colecistostomia", "vesicula em porcelana", "colelitiase"]),
    ("vias-biliares", "Coledocolitíase e CPRE",
     ["coledocolitiase", "cpre", "esfincterotomia", "colangiografia intraoperatoria", "asge"]),
    ("vias-biliares", "Colangite aguda",
     ["colangite", "triade de charcot", "pentade de reynolds"]),
    ("vias-biliares", "Lesão biliar e visão crítica de segurança",
     ["lesao biliar", "strasberg", "visao critica", "triangulo de calot"]),
    ("vias-biliares", "Câncer de vesícula e colangiocarcinoma",
     ["cancer de vesicula", "colangiocarcinoma", "bismuth-corlette", "bismuth"]),
    ("vias-biliares", "Cisto de colédoco e íleo biliar",
     ["cisto de coledoco", "todani", "ileo biliar", "rigler", "triade de quincke"]),
    # ── Pâncreas ─────────────────────────────────────────────────────
    ("pancreas", "Pancreatite aguda — diagnóstico e gravidade",
     ["pancreatite aguda", "ranson", "balthazar", "atlanta", "amilase", "lipase"]),
    ("pancreas", "Necrose pancreática e step-up",
     ["necrose pancreatica", "necrosectomia", "step-up", "panter", "walled-off", "coleccao infectada", "necrose infectada"]),
    ("pancreas", "Pancreatite crônica",
     ["pancreatite cronica", "puestow", "frey"]),
    ("pancreas", "Neoplasias císticas e IPMN",
     ["ipmn", "neoplasia cistica", "cistoadenoma"]),
    ("pancreas", "Adenocarcinoma de pâncreas",
     ["adenocarcinoma de pancreas", "ressecabilidade", "duodenopancreatectomia", "whipple", "ca 19-9", "iceterica obstrutiva indolor", "icterica obstrutiva indolor"]),
    ("pancreas", "Tumores neuroendócrinos pancreáticos",
     ["gastrinoma", "zollinger", "insulinoma", "triangulo de passaro",
      "glucagonoma", "vipoma", "somatostatinoma", "tumor neuroendocrino",
      "neuroendocrino", "enets", "cromogranina", "octreotide", "octreoscan",
      "dotatate", "verner-morrison", "eritema necrolitico",
      "neoplasia endocrina multipla", "peptideo c", "hipoglicemia factica",
      "sulfonilureia", "whipple - triade"]),
    ("pancreas", "Fístula pancreática pós-operatória",
     ["fistula pancreatica", "isgps"]),
    # ── Coloproctologia ──────────────────────────────────────────────
    ("coloproctologia", "Doença diverticular e Hinchey",
     ["diverticulite", "hinchey", "doenca diverticular", "diabolo", "avod"]),
    ("coloproctologia", "Câncer colorretal — rastreio e pólipos",
     ["rastreamento de cancer colorretal", "polipo", "polipectomia", "adenoma-carcinoma", "haggitt", "kikuchi", "colonoscopia"]),
    ("coloproctologia", "Câncer de reto",
     ["cancer de reto", "neoadjuvancia", "watch and wait", "excisao total do mesorreto", "reto medio", "margens cirurgicas no cancer de reto"]),
    ("coloproctologia", "Câncer de cólon e linfadenectomia",
     ["cancer de colon", "colon direito", "numero minimo de linfonodos", "hemicolectomia"]),
    ("coloproctologia", "Síndromes hereditárias — Lynch e PAF",
     ["lynch", "polipose adenomatosa familiar", "paf", "spigelman"]),
    ("coloproctologia", "Doença inflamatória intestinal",
     ["crohn", "retocolite", "colite ulcerativa"]),
    ("coloproctologia", "Volvo e pseudo-obstrução",
     ["volvo", "ogilvie", "pseudo-obstrucao", "ceco - diametro", "diametro critico", "lei de laplace"]),
    ("coloproctologia", "Hemorragia digestiva baixa",
     ["hemorragia digestiva baixa", "hdb", "angiodisplasia"]),
    ("coloproctologia", "Doença anorretal benigna",
     ["hemorroid", "fissura anal", "fistula anal", "abscesso perianal", "goodsall", "parks", "milligan", "canal anal"]),
    ("coloproctologia", "Câncer de canal anal",
     ["canal anal - tratamento", "carcinoma epidermoide do canal anal", "nigro"]),
    ("coloproctologia", "Colite por C. difficile e ostomias",
     ["pseudomembranosa", "difficile", "ileostomia", "colostomia", "hartmann"]),
    # ── Apêndice e delgado ───────────────────────────────────────────
    ("apendice-delgado", "Apendicite aguda",
     ["apendicite", "alvarado", "mantrels", "apendicectomia", "coda", "fleimao apendicular", "rovsing", "blumberg", "dunphy", "psoas", "obturador", "ten horn", "aaron"]),
    ("apendice-delgado", "Obstrução intestinal e bridas",
     ["obstrucao intestinal", "brida", "aderencias", "obstrutivo"]),
    ("apendice-delgado", "Divertículo de Meckel",
     ["meckel"]),
    ("apendice-delgado", "Tumores neuroendócrinos do delgado e apêndice",
     ["tumor neuroendocrino", "carcinoide"]),
    ("apendice-delgado", "Fístula enterocutânea",
     ["fistula enterocutanea", "fistula digestiva", "friends"]),
    ("apendice-delgado", "Isquemia mesentérica",
     ["isquemia mesenterica", "wilkie", "pinca aortomesenterica"]),
    # ── Esôfago ──────────────────────────────────────────────────────
    ("esofago", "Megaesôfago chagásico e graus de Rezende",
     ["megaesofago", "rezende", "chagasic", "chagasico"]),
    ("esofago", "Acalasia",
     ["acalasia", "heller", "poem", "manometria"]),
    ("esofago", "DRGE e fundoplicatura",
     ["drge", "refluxo", "fundoplicatura", "nissen", "phmetria"]),
    ("esofago", "Esôfago de Barrett",
     ["barrett", "ablacao por radiofrequencia", "mucosectomia", "supressao acida",
      "pos-ablacao", "displasia de alto grau do esofago"]),
    ("esofago", "Esofagite cáustica e eosinofílica",
     ["soda caustica", "ingestao de caustico", "esofagite eosinofilica",
      "impactacao alimentar", "zargar"]),
    ("esofago", "Câncer de esôfago",
     ["cancer de esofago", "esofagectomia", "cross"]),
    ("esofago", "Divertículos esofágicos e Zenker",
     ["zenker", "diverticulo esofagic", "diverticulos esofagicos", "killian"]),
    ("esofago", "Perfuração esofágica — Boerhaave",
     ["boerhaave", "mallory-weiss", "perfuracao esofagica"]),
    # ── Estômago e duodeno ───────────────────────────────────────────
    ("estomago-duodeno", "Úlcera péptica e perfuração",
     ["ulcera peptica", "ulcera duodenal", "ulcera gastrica", "johnson", "ulcera perfurada", "graham"]),
    ("estomago-duodeno", "Hemorragia digestiva alta e Forrest",
     ["forrest", "hemorragia digestiva alta", "hda", "rockall", "dieulafoy", "hematemese"]),
    ("estomago-duodeno", "Câncer gástrico",
     ["cancer gastric", "gastrectomia", "linfadenectomia", "flot", "cdh1", "linfoma gastric", "malt"]),
    ("estomago-duodeno", "GIST",
     ["gist", "imatinibe"]),
    ("estomago-duodeno", "Síndromes pós-gastrectomia",
     ["dumping", "grelina", "sindrome de saint", "triade de saint"]),
    # ── Fígado ───────────────────────────────────────────────────────
    ("figado", "Tumores hepáticos benignos",
     ["adenoma hepatocelular", "hemangioma", "hiperplasia nodular", "tumores hepaticos benignos"]),
    ("figado", "Hepatocarcinoma, BCLC e transplante",
     ["hepatocarcinoma", "bclc", "criterios de milao", "carcinoma hepatocelular"]),
    ("figado", "Metástases hepáticas",
     ["metastase hepatica"]),
    ("figado", "Abscessos hepáticos",
     ["abscesso hepatico", "abscesso amebiano"]),
    ("figado", "Cirrose, Child-Pugh e MELD",
     ["child-pugh", "meld", "cirrotico", "risco cirurgico no cirrotico"]),
    ("figado", "Hipertensão portal e varizes",
     ["hipertensao portal", "varizes", "terlipressina", "baveno", "hda varicosa", "tips"]),
    # ── Hérnias ──────────────────────────────────────────────────────
    ("hernias", "Hérnia inguinal — anatomia e técnicas",
     ["hernia inguinal", "lichtenstein", "bassini", "shouldice", "mcvay", "hesselbach", "nyhus", "herniasurge", "tep x tapp", "tapp", "triangulo da dor", "triangulo da morte", "corona mortis", "ligamento de cooper"]),
    ("hernias", "Hérnia femoral e encarceramento",
     ["hernia femoral", "encarcerad", "estrangulad", "hernia de richter", "richter"]),
    ("hernias", "Hérnia incisional e separação de componentes",
     ["hernia incisional", "separacao de componentes", "eventracao"]),
    ("hernias", "Fechamento de parede e técnica STITCH",
     ["stitch", "small bites", "fechamento da parede", "fechamento de laparotomia", "deiscencia de parede"]),
    ("hernias", "Tumor desmoide",
     ["desmoide"]),
    # ── Trauma ───────────────────────────────────────────────────────
    ("trauma", "Avaliação inicial e via aérea no trauma",
     ["via aerea definitiva", "xabcde", "avaliacao primaria", "glasgow", "videolaringoscopia", "queimadura de via aerea"]),
    ("trauma", "Choque hemorrágico e transfusão maciça",
     ["choque hemorragico", "transfusao macica", "hipotensao permissiva", "acido tranexamico", "triade letal", "1:1:1"]),
    ("trauma", "Trauma torácico",
     ["hemotorax", "pneumotorax hipertensivo", "trauma toracico", "triade de beck",
      "tamponamento", "toracotomia", "torax instavel", "torax flacido",
      "flail chest", "gradil costal", "movimento paradoxal", "fratura de costela"]),
    ("trauma", "Trauma abdominal e FAST",
     ["fast", "trauma abdominal", "laparotomia no trauma", "evisceracao", "lavado peritoneal"]),
    ("trauma", "Trauma de baço e fígado",
     ["trauma esplenico", "lesao esplenica", "trauma hepatico", "aast",
      "manobra de pringle", "sinal de kehr", "hematoma subcapsular",
      "lesao hepatica", "packing hepatico", "empacotamento hepatico"]),
    ("trauma", "Trauma vascular e de extremidades",
     ["trauma vascular", "sindrome compartimental", "rabdomiolise", "sinais maiores"]),
    ("trauma", "Trauma de bacia e choque neurogênico",
     ["fratura de bacia", "choque neurogenico", "tetraparesia"]),
    # ── Endócrino / cabeça e pescoço ─────────────────────────────────
    ("endocrino-cp", "Nódulo de tireoide e Bethesda",
     ["nodulo de tireoide", "bethesda", "nodulo tireoidiano", "paaf"]),
    ("endocrino-cp", "Câncer de tireoide",
     ["carcinoma papilifero", "carcinoma folicular", "carcinoma medular", "tireoidectomia"]),
    ("endocrino-cp", "Paratireoide e hipercalcemia",
     ["hiperparatireoidismo", "paratireoide"]),
    ("endocrino-cp", "Adrenal e feocromocitoma",
     ["feocromocitoma", "incidentaloma adrenal", "adrenal", "metanefrinas"]),
    ("endocrino-cp", "Cervical congênito e glândulas salivares",
     ["sistrunk", "tireoglosso", "parotida", "sjogren"]),
    # ── Perioperatório ───────────────────────────────────────────────
    ("perioperatorio", "Sepse cirúrgica e controle do foco",
     ["sepse", "qsofa", "controle do foco", "vasopressor", "noradrenalina", "lactato"]),
    ("perioperatorio", "Infecção de sítio cirúrgico e antibioticoprofilaxia",
     ["infeccao de sitio cirurgico", "antibioticoprofilaxia", "feridas cirurgicas", "profilaxia cirurgica"]),
    ("perioperatorio", "Cicatrização, fios e enxertos",
     ["cicatrizacao", "fios cirurgicos", "enxerto de pele", "fio absorvivel",
      "fio inabsorvivel", "primeira intencao"]),
    ("perioperatorio", "Nutrição perioperatória",
     ["nutricao", "realimentacao", "nrs 2002", "espen", "braspen", "jejum"]),
    ("perioperatorio", "ERAS e cuidados pós-operatórios",
     ["eras", "clavien-dindo", "lesao por pressao", "hipocalemia"]),
    ("perioperatorio", "Anastomoses e deiscência",
     ["deiscencia de anastomose", "anastomose colorretal"]),
    ("perioperatorio", "Tromboprofilaxia",
     ["tromboprofilaxia", "profilaxia de tvp"]),
    ("perioperatorio", "Hipertensão intra-abdominal",
     ["hipertensao intra-abdominal", "sindrome compartimental abdominal",
      "pressao intra-abdominal"]),
    ("perioperatorio", "Acesso venoso central",
     ["acesso venoso central", "puncao venosa"]),
    # ── Anestesia e via aérea ────────────────────────────────────────
    ("anestesia-via-aerea", "Anestésicos locais e toxicidade",
     ["anestesico local", "anestesicos locais", "lidocaina", "bupivacaina",
      "ropivacaina", "mepivacaina", "prilocaina", "asra", "dose maxima"]),
    ("anestesia-via-aerea", "Indução e bloqueadores neuromusculares",
     ["succinilcolina", "cetamina", "propofol", "etomidato", "bloqueador neuromuscular", "hipertermia maligna"]),
    ("anestesia-via-aerea", "Ventilação mecânica protetora",
     ["ventilacao protetora", "driving pressure", "ardsnet", "sdra"]),
    # ── Baço e transplante ───────────────────────────────────────────
    ("baco-transplante", "Esplenectomia e suas consequências",
     ["esplenectomia", "trombocitose", "vacina", "opsi", "baco"]),
    ("baco-transplante", "Transplante de órgãos",
     ["transplante", "morte encefalica", "imunossupress"]),
    # ── Vascular ─────────────────────────────────────────────────────
    ("vascular", "Aneurismas periféricos e pseudoaneurisma",
     ["aneurisma", "pseudoaneurisma", "popliteia", "poplitea"]),
    ("vascular", "Doença arterial periférica",
     ["fontaine", "rutherford", "tornozelo-braquial", "claudicacao", "doenca arterial periferica"]),
    ("vascular", "Isquemia arterial aguda",
     ["isquemia arterial aguda", "6 p", "embolectomia"]),
    ("vascular", "Doença venosa e TVP",
     ["trombose venosa profunda", "tvp", "varizes de membros"]),
    # ── Torácica ─────────────────────────────────────────────────────
    ("toracica", "Derrame pleural e pneumotórax",
     ["derrame pleural", "criterios de light", "pneumotorax espontaneo", "drenagem pleural", "quilotorax", "bts"]),
    ("toracica", "Câncer de pulmão e mediastino",
     ["cancer de pulmao", "mediastino", "ebus", "mediastinoscopia"]),
    ("toracica", "Traqueia e parede torácica",
     ["estenose traqueal", "pectus", "ortese", "traqueostomia"]),
    # ── Pele, partes moles e sarcomas ────────────────────────────────
    ("pele-sarcomas", "Melanoma e linfonodo sentinela",
     ["melanoma", "breslow", "clark", "linfonodo sentinela", "mslt"]),
    ("pele-sarcomas", "Câncer de pele não melanoma",
     ["basocelular", "epidermoide", "carcinoma espinocelular"]),
    ("pele-sarcomas", "Sarcomas de partes moles",
     ["sarcoma", "strass", "tarpswg"]),
    ("pele-sarcomas", "Queimaduras",
     ["queimadura", "parkland", "superficie queimada"]),
    ("pele-sarcomas", "Infecção necrotizante de partes moles",
     ["necrotizante", "fasciite", "fournier"]),
    ("pele-sarcomas", "Retalhos e reconstrução",
     ["retalho", "reconstrucao mamaria", "tram", "enxerto de nervo", "sural"]),
    # ── Videolaparoscopia ────────────────────────────────────────────
    ("videolaparoscopia", "Fisiologia do pneumoperitônio",
     ["alteracoes fisiologicas do pneumoperitonio", "capnoperitonio",
      "pressao de trabalho", "insuflacao de co2", "pneumoperitonio -"]),
    ("videolaparoscopia", "Complicações e contraindicações da laparoscopia",
     ["embolia gasosa", "contraindicacao absoluta a laparoscopia", "ponto de palmer", "laparoscopia"]),
    # ── Bariátrica ───────────────────────────────────────────────────
    ("bariatrica", "Indicações e Resolução CFM 2.429/2025",
     ["cirurgia bariatrica", "bariatrica", "2.429", "indicacoes classicas"]),
    ("bariatrica", "Complicações da bariátrica",
     ["bypass gastrico", "gastrectomia vertical", "fistula pos-gastrectomia", "sleeve"]),
    # ── Pediátrica ───────────────────────────────────────────────────
    ("pediatrica", "Emergências do recém-nascido",
     ["enterocolite necrosante", "gastrosquise", "onfalocele", "atresia",
      "pneumatose intestinal do recem-nascido"]),
    ("pediatrica", "Estenose hipertrófica de piloro",
     ["estenose hipertrofica de piloro"]),
    ("pediatrica", "Corpos estranhos e parede umbilical",
     ["corpo estranho", "corpos estranhos", "granuloma umbilical"]),
    ("pediatrica", "Cirurgia pediátrica — outros",
     ["kasai", "atresia de vias biliares", "cordao triangular", "pediatric"]),
    # ── Mama ─────────────────────────────────────────────────────────
    ("mama", "Nódulo mamário e BI-RADS",
     ["bi-rads", "nodulo mamario", "mamografia"]),
    ("mama", "Tratamento cirúrgico da mama",
     ["cirurgia conservadora da mama", "mastectomia"]),
    ("mama", "Câncer de mama — aula completa",
     ["cancer de mama", "subtipos moleculares", "niveis de berg"]),
    # ── Nefrologia ───────────────────────────────────────────────────
    ("nefrologia", "Doença renal crônica",
     ["doenca renal cronica", "drc", "taxa de filtracao glomerular", "tfg",
      "kdigo", "cistatina", "albuminuria", "ckd-epi", "nefroprotecao"]),
    # ── Urologia ─────────────────────────────────────────────────────
    ("urologia", "Litíase urinária e cólica renal",
     ["colica renal", "calculo ureteral", "litiase", "pionefrose", "calculo obstrutivo"]),
    ("urologia", "Escroto agudo e massa testicular",
     ["torcao testicular", "prehn", "escroto agudo", "cremasterico"]),
    ("urologia", "Tumores de testículo",
     ["massa testicular", "seminoma", "nsgct", "nao-seminoma", "celulas germinativas",
      "saco vitelino", "yolk sac", "rplnd", "orquiectomia", "tumor de testiculo",
      "tumor testicular", "isocromossomo", "coriocarcinoma", "teratoma"]),
    ("urologia", "Próstata — HPB e câncer",
     ["hpb", "hiperplasia prostatica", "cancer de prostata", "psa"]),
    ("urologia", "Trauma urológico",
     ["trauma renal", "trauma de uretra", "uretrografia"]),
    ("urologia", "Prepúcio e infecções genitais",
     ["fimose", "parafimose", "ulceras genitais", "ists",
      "infeccao sexualmente transmissivel", "cancro", "sifilis"]),
    # ── Oncologia geral ──────────────────────────────────────────────
    ("oncologia", "Princípios de ressecção oncológica",
     ["ressecao r0", "r0, r1", "margem de ressecao", "margem cirurgica",
      "neoadjuvancia - objetivos", "carcinogenese", "linfonodo sentinela"]),
    ("oncologia", "TNM e estadiamento",
     ["tnm", "estadiamento"]),
    ("oncologia", "Marcadores tumorais",
     ["marcadores tumorais", "marcador tumoral"]),
    ("oncologia", "Síndromes genéticas em cirurgia",
     ["sindrome genetica", "mutacao germinativa", "neoplasia endocrina multipla",
      "nem 1", "nem 2", "nem 4", "li-fraumeni", "cdkn1b"]),
    # ── Ética ────────────────────────────────────────────────────────
    ("etica", "Consentimento e autonomia",
     ["consentimento", "autonomia", "recusa terapeutica", "testemunha de jeova", "adolescente e autonomia"]),
    ("etica", "Sigilo médico",
     ["sigilo medico", "doenca transmissivel", "quebra de sigilo"]),
    ("etica", "Terminalidade",
     ["ortotanasia", "distanasia", "eutanasia", "cuidados paliativos"]),
    ("etica", "Resoluções do CFM",
     ["resolucao cfm", "codigo de etica", "cfm n", "2.217", "2.232"]),
    # ── Anatomia ─────────────────────────────────────────────────────
    ("anatomia", "Vascularização abdominal",
     ["tronco celiaco", "mesenterica superior", "mesenterica inferior", "riolan", "drummond", "arcada pancreatoduodenal", "veia porta", "arteria hepatica"]),
    ("anatomia", "Segmentação hepática",
     ["couinaud", "lobo caudado", "cantlie", "rouviere", "segmentacao hepatica"]),
    ("anatomia", "Referências da parede e do períneo",
     ["ligamento de treitz", "parede abdominal - arterias", "anatomia cirurgica"]),
    # ── Transversais (fallback dos decks do autor) ───────────────────
    ("transversais", "Escores e classificações", []),
    ("transversais", "Eponímias, sinais e tríades", []),
    ("transversais", "Números-limite", []),
    ("transversais", "Outros conceitos", []),
]

# Área do simulado (cabeçalho do gabarito) → slug
AREA_DO_SIMULADO = {
    "vias biliares e vesicula": "vias-biliares",
    "pancreas": "pancreas",
    "coloproctologia": "coloproctologia",
    "apendice e intestino delgado": "apendice-delgado",
    "esofago": "esofago",
    "estomago e duodeno": "estomago-duodeno",
    "figado e hipertensao portal": "figado",
    "hernias e parede abdominal": "hernias",
    "trauma": "trauma",
    "cabeca e pescoco / endocrino": "endocrino-cp",
    "pre e pos-operatorio, nutricao e infeccao": "perioperatorio",
    "anestesia, via aerea e ventilacao": "anestesia-via-aerea",
    "baco, hematologia e transplante": "baco-transplante",
    "cirurgia vascular": "vascular",
    "cirurgia toracica": "toracica",
    "cirurgia pediatrica": "pediatrica",
    "pele, partes moles e sarcomas": "pele-sarcomas",
    "oncologia geral e genetica": "oncologia",
    "etica medica e medicina legal": "etica",
}

# Deck do autor → tema de fallback quando nenhuma palavra-chave casa
FALLBACK_POR_DECK = {
    "01_Transversais escores": ("transversais", "Escores e classificações"),
    "01_Transversais eponimos": ("transversais", "Eponímias, sinais e tríades"),
    "01_Transversais numeros": ("transversais", "Números-limite"),
    "02_Nucleo anatomia": ("anatomia", "Vascularização abdominal"),
    "02_Nucleo colon_reto": ("coloproctologia", "Doença diverticular e Hinchey"),
    "02_Nucleo esofago_estomago": ("estomago-duodeno", "Câncer gástrico"),
    "02_Nucleo hernias": ("hernias", "Hérnia inguinal — anatomia e técnicas"),
    "02_Nucleo oncologia_geral": ("oncologia", "Princípios de ressecção oncológica"),
    "02_Nucleo pancreas": ("pancreas", "Pancreatite aguda — diagnóstico e gravidade"),
    "02_Nucleo perioperatorio": ("perioperatorio", "ERAS e cuidados pós-operatórios"),
    "02_Nucleo trauma": ("trauma", "Avaliação inicial e via aérea no trauma"),
    "02_Nucleo vias_biliares": ("vias-biliares", "Colecistite aguda e critérios de Tóquio"),
    "03_Baratos endocrino_cp": ("endocrino-cp", "Nódulo de tireoide e Bethesda"),
    "03_Baratos etica": ("etica", "Resoluções do CFM"),
    "03_Baratos figado": ("figado", "Tumores hepáticos benignos"),
    "03_Baratos urologia": ("urologia", "Litíase urinária e cólica renal"),
    "04_Cauda cauda": ("transversais", "Outros conceitos"),
    "04_Cauda mama_video_torax": ("transversais", "Outros conceitos"),
    "05_Conduta proximo_passo": ("transversais", "Outros conceitos"),
}

# Módulo do ebook → área
MODULO_EBOOK = {
    "1": "transversais", "2": "esofago", "3": "urologia", "4": "pancreas",
    "5": "hernias", "6": "toracica", "7": "vascular", "8": "pele-sarcomas",
    "9": "pediatrica",
}
